### ISSUE TITLE
Two questions about the model training: weight mismatch and yolov3_480000.h5

### ISSUE THREAD

**Issue by jianhua2022** [henghuiding/Vision-Language-Transformer#1]
Hi, 
     I am running your code for model training, but I have two questions: 
1) How to generate the weights of yolov3_480000.h5. I try to generate the yolov3_480000.h5 follow the Keras implementation of YOLOv3 by Converting the Darknet YOLO model to a Keras model: python convert.py yolov3.cfg yolov3.weights model_data/yolo.h5. So is it right?
2) After generating the yolov3_480000.h5, I start to train the model. But it shows some warming information, why?
![image](https://user-images.githubusercontent.com/28485169/133870120-b9b0ddcb-8eb9-4c2d-9d45-3a161c2816aa.png)

**Comment by changliu19** [comment]
Hi Jianhua,

Thanks for your questions.

1. Please follow the instructions about "Pretrained Backbones" in the README file to prepare the backbone weights.

2. This is expected. Don't worry😃
