### ISSUE TITLE
What's the gpu device that can support this model?

### ISSUE THREAD

**Issue by clownrat6** [henghuiding/Vision-Language-Transformer#2]
Is the batch size 128? I can't deploy the model on single 11 GB NVIDIA 2080 Ti when setting batch size is 16.

**Comment by henghuiding** [comment]
Hi,

The model is trained with V100. You can use smaller batch size when training with 11GB 2080Ti.

**Comment by clownrat6** [comment]
Thank you. I get it. The batch size will be assigned to each gpu. So the samples of one gpu is `batch_size / num_gpus`

**Comment by LeungWaiHo** [comment]
> Hi,
> 
> The model is trained with V100. You can use smaller batch size when training with 11GB 2080Ti.

Dear author, how many V100 do you use to train the models?

**Comment by Lu-Tan** [comment]
1080Ti * 4 is also ok. But 3090Ti isn't.
