### ISSUE TITLE
How to train on the custom data set?

### ISSUE THREAD

**Issue by YunLongPan** [henghuiding/Vision-Language-Transformer#3]

**Comment by changliu19** [comment]
Hi Yunlong,

Briefly speaking, you need to prepare a dataset annotation JSON file, then specify the path to the image folder and target mask folder in the config file. For details please check: 

https://github.com/henghuiding/Vision-Language-Transformer/blob/9b24015566fa820e3eddbbd8942fa44512ec1b3c/data/data_process_v2.py#L77

https://github.com/henghuiding/Vision-Language-Transformer/blob/9b24015566fa820e3eddbbd8942fa44512ec1b3c/loader/loader.py#L93

**Comment by YunLongPan** [comment]
Thank you!
















At 2021-10-06 18:30:04, "ntuLC" ***@***.***> wrote:

Hi Yunlong,

Briefly speaking, you need to prepare a dataset annotation JSON file, then specify the path to the image folder and target mask folder in the config file. For details please check:

https://github.com/henghuiding/Vision-Language-Transformer/blob/9b24015566fa820e3eddbbd8942fa44512ec1b3c/data/data_process_v2.py#L77

https://github.com/henghuiding/Vision-Language-Transformer/blob/9b24015566fa820e3eddbbd8942fa44512ec1b3c/loader/loader.py#L93
