### ISSUE TITLE
About training speed.

### ISSUE THREAD

**Issue by chaoqunwangcs** [henghuiding/Vision-Language-Transformer#4]
Thanks for the great work! I wonder about the training speed? I tried to train the model on 2*V100 with batch size 256, but the training process is too slow and about 10 hours per epoch, is it normal?

**Comment by changliu19** [comment]
Dear Chaoqun,

Thanks for your interest! On our system, normally it takes about 15-20min to train an epoch on refcoco and refcocop, and about 20-25min on refcocog.

**Comment by chaoqunwangcs** [comment]
Thanks! I find that the GPUs are not utilized and I will try to fix it.

**Comment by wangchaoqun56** [comment]
I have fixed the problem, and it takes about 1000s for training and 8min for validation per epoch with batch size 32 on 2*V100, but I can only config the batch size as 16 per V100 with 32G memory or 8 for RTX2080 with 11G memory. If I try to enlarge the batch size, the oom error appears. It is abnormal and I will try to fix it.
